### ISSUE TITLE
No Code

### ISSUE THREAD

**Issue by thies23** [PhilmacFLy/wheretoeat#1]
I would like to let "wheretoeat" choose where i'm going to eat, but the software doesn't compile due to non existent code.
Please fix!
I'm Starving!

**Comment by PhilmacFLy** [comment]
I'm sorry I overlooked that Bug.
I will take care of it immediatley

**Comment by PhilmacFLy** [comment]
Bug should be solved now with the first release.

**Comment by thies23** [comment]
That wasn't immediately, but i appreciate the bugfix.

Thanks a lot <3
